package it.mbkj.lib.base

import it.mbkj.lib.LibAcitivity

object ArouterAddress {
    const val LibAcitivity="/lib/libactivity"
    const val PERSONCENTERFRAGMENT="/personcenter/personcenterfragment"
    const val HOMEPAGEFRAGMENT="/homepage/homepagefragment"
    const val TRADCENTERFRAGMENT="/tradecenter/tradcenterfragment"
    const val XINGQIUFRAGMENT="/xingqiu/xingqiufragment"
    const val PLEDGEHALLACTIVITY="/personcenter/pledgehallactivity"
    const val MYORDERACTIVITY="/personcenter/myorderactivity"
    const val ORDERDETAILACTIVITY="/personcenter/orderdetailactivity"
    const val MYJIJIAACTIVITY="/personcenter/myjijiaactivity"
    const val MYTEAMACTIVITY="/personcenter/myteamactivity"
    const val ZICHANXINXIACTIVITY="/personcenter/zichanxinxiactivity"
    const val RECHARGEACTIVITY="/personcenter/rechargeactivity"
    const val RECHARGERECORDACTIVITY="/personcenter/rechargerecordactivity"
    const val WITHDRAWACTIVITY="/personcenter/withdrawactivity"
    const val PROFITRECORDACTIVITY="/personcenter/profitrecordactivity"
    const val SETTINGACTIVITY="/personcenter/settingactivity"
    const val WITHDRAWRECORDACTIVITY="/personcenter/withdrawrecordactivity"
    const val TRANFERACTIVITY="/personcenter/tranferactivity"
    const val TRANSFERRECORDACTIVITY="/personcenter/transferrecordactivity"
    const val UPDATEDEALPASSWORDACTIVITY="/personcenter/updatedealpasswordactivity"
    const val UPDATELOGINACTIVITY="/personcenter/updateloginactivity"
    const val LOGINACTIVITY="/login/loginactivity"
    const val BUYBAOACTIVITY="/tradecenter/buybaoactivity"
    const val BUYLISTACTIVITY="/tradecenter/buylistactivity"
    const val SELLLISTACTIVITY="/tradecenter/selllistactivity"
    const val REGISTERACTIVITY="/login/registeractivity"
    const val FORGETPWDACTIVITY="/login/forgetpwdactivity"
    const val MAINACTIVITY="/app/mainactivity"
    const val GONGGAOACTIVITY="/homepage/gonggaoactivity"
    const val GONGGAODETAILACTIVITY="/homepage/gonggaodetailactivity"
    const val INVITEFRIENDSACTIVITY="/personcenter/invitefriendsactivity"
    const val NEWACTIVITY="/tradcenter/newactivity"
    const val CONACTUSACTIVITY="/personcenter/conactusactivity"
}